name: Deploy Workflow

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Clona el repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Add execute permissions to tests script
        run: chmod +x ./run-tests.sh

      - name: Run tests
        run: npm run test:linux